fix(Send transaction):Fix user not being to send token due to depreca…
allanclempe/ether-wallet-flutter pull request #26
Opened 2022-04-17 20:54 UTC by Baksman

…ted package api

2022-04-20 10:22 UTC, allanclempe commented
first at all, thanks for the contrib @Baksman

2022-04-20 10:27 UTC, allanclempe requested changes

2022-04-20 10:27 UTC, allanclempe commented on lib/service/contract_service.dart
> +  EthPrivateKey  getCredentials(String privateKey) => EthPrivateKey.fromHex(privateKey);
this shouldn't need implementation. consider having the method signature.
`EthPrivateKey getCredentials(String privateKey);`

2022-04-20 10:27 UTC, allanclempe commented on lib/service/contract_service.dart
> +  // @override
consider removing commented code.

2022-04-20 10:27 UTC, allanclempe commented on lib/service/contract_service.dart
> +      // TODO: Fix send txn
this should be working already, what exactly needs to be fixed?

2022-04-20 10:27 UTC, allanclempe commented on pubspec.yaml
> +  json_rpc_2: ^3.0.1
is it being used? if not could you please remove it,

2022-04-23 13:20 UTC, Baksman commented
> Okay  fixed as requested

2022-04-26 05:33 UTC, merged